In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4])

In [6]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
arr1.ndim

2

In [8]:
arr.ndim

1

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat = np.matrix(l)

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [14]:
mat

matrix([[1, 2, 3, 4]])

In [15]:
arr

array([1, 2, 3, 4])

In [16]:
l

[1, 2, 3, 4]

In [17]:
a = arr

In [18]:
a

array([1, 2, 3, 4])

In [19]:
arr

array([1, 2, 3, 4])

In [20]:
a[0] = 100

In [21]:
a

array([100,   2,   3,   4])

In [22]:
# Shallow copy operation
arr

array([100,   2,   3,   4])

In [23]:
# Deep copy
b = np.copy(arr)

In [24]:
b

array([100,   2,   3,   4])

In [25]:
b[0] = 200

In [26]:
b

array([200,   2,   3,   4])

In [27]:
arr

array([100,   2,   3,   4])

In [28]:
np.fromfunction(lambda i,j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [29]:
np.fromfunction(lambda i,j : i+j, (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [30]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [31]:
iterables = (i*i for i in range(1,6))

In [32]:
np.fromiter(iterables, float)

array([ 1.,  4.,  9., 16., 25.])

In [33]:
np.fromstring("23 45 67", sep = " ")

array([23., 45., 67.])

In [34]:
arr

array([100,   2,   3,   4])

In [35]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.ndim

1

In [37]:
arr1.ndim

2

In [38]:
arr.size

4

In [39]:
arr1.size

9

In [40]:
arr.shape

(4,)

In [41]:
arr1.shape

(3, 3)

In [42]:
arr.dtype

dtype('int32')

In [43]:
arr1.dtype

dtype('int32')

In [44]:
list(range(5))

[0, 1, 2, 3, 4]

In [45]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [46]:
list(np.arange(0.4,5,0.4))

[0.4,
 0.8,
 1.2000000000000002,
 1.6,
 2.0,
 2.4,
 2.8000000000000003,
 3.2,
 3.6,
 4.0,
 4.4,
 4.800000000000001]

In [47]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [48]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.ones(6)*4

array([4., 4., 4., 4., 4., 4.])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [53]:
np.ones((3,4,2,3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [54]:
arr = np.ones((3,4))

In [55]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [56]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
arr*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [58]:
np.empty((3,4))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [59]:
arr3 = np.eye(4)

In [60]:
import pandas as pd
pd.DataFrame(arr3)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [61]:
np.random.rand(2,4)

array([[0.76209489, 0.82444973, 0.81057887, 0.6974236 ],
       [0.05712508, 0.08681383, 0.42217588, 0.38788408]])

In [62]:
np.random.randn(2,4)

array([[-0.45294104, -2.47973583, -0.79847138, -0.88450609],
       [ 0.93777046,  0.58383487, -0.56673542,  1.17807487]])

In [63]:
arr2 = np.random.randint(2,10,(3,4))

In [64]:
arr2

array([[2, 5, 6, 5],
       [5, 4, 6, 9],
       [8, 3, 4, 6]])

In [65]:
arr2.size

12

In [66]:
arr2.shape

(3, 4)

In [67]:
arr2.reshape(6,2)

array([[2, 5],
       [6, 5],
       [5, 4],
       [6, 9],
       [8, 3],
       [4, 6]])

In [68]:
arr2.reshape(4,3)

array([[2, 5, 6],
       [5, 5, 4],
       [6, 9, 8],
       [3, 4, 6]])

In [69]:
arr2.reshape(4,-1)

array([[2, 5, 6],
       [5, 5, 4],
       [6, 9, 8],
       [3, 4, 6]])

In [70]:
arr2.reshape(-23,4)

array([[2, 5, 6, 5],
       [5, 4, 6, 9],
       [8, 3, 4, 6]])

In [71]:
arr2.reshape(2,2,3)

array([[[2, 5, 6],
        [5, 5, 4]],

       [[6, 9, 8],
        [3, 4, 6]]])

In [72]:
arr1 = np.random.randint(1,10,(5,6))

In [73]:
arr1

array([[2, 3, 5, 6, 2, 7],
       [7, 3, 5, 5, 4, 9],
       [7, 7, 5, 1, 2, 8],
       [3, 9, 9, 6, 1, 2],
       [4, 4, 6, 1, 2, 4]])

In [74]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False, False, False, False, False]])

In [75]:
arr1[arr1>8]

array([9, 9, 9])

In [76]:
arr1

array([[2, 3, 5, 6, 2, 7],
       [7, 3, 5, 5, 4, 9],
       [7, 7, 5, 1, 2, 8],
       [3, 9, 9, 6, 1, 2],
       [4, 4, 6, 1, 2, 4]])

In [77]:
arr1[0,[0,1]]

array([2, 3])

In [78]:
arr1[2:4,[2,3,4]]

array([[5, 1, 2],
       [9, 6, 1]])

In [79]:
arr4 = np.random.randint(1,3,(3,3))

In [80]:
arr5 = np.random.randint(1,3,(3,3))

In [81]:
arr4

array([[2, 2, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [82]:
arr5

array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [83]:
arr4+arr5

array([[4, 3, 2],
       [3, 4, 2],
       [3, 4, 2]])

In [84]:
arr4*arr5

array([[4, 2, 1],
       [2, 4, 1],
       [2, 4, 1]])

In [85]:
# Matrix multiplication
arr4@arr5

array([[8, 8, 5],
       [8, 8, 5],
       [6, 7, 4]])

In [86]:
arr4/arr5

array([[1. , 2. , 1. ],
       [2. , 1. , 1. ],
       [0.5, 1. , 1. ]])

In [87]:
arr1/0

C:\Users\shara\AppData\Local\Temp\ipykernel_9448\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [88]:
# Numpy - Broadcasting(doing some operation on every element of array)

In [89]:
arr6 = np.zeros((3,4))

In [90]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
arr6+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [92]:
arr7 = np.array([1,2,3,4])

In [93]:
arr6+arr7

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [94]:
b = np.array([[3,4,5]])

In [95]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
arr = arr6+b.T

In [97]:
np.sqrt(arr)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [98]:
arr

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [99]:
np.log10(arr)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [100]:
np.exp(arr)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [101]:
np.min(arr)

3.0

In [102]:
np.max(arr)

5.0

In [103]:
print("Hello Sharath PD")

Hello Sharath PD


In [104]:
# Numpy - Array Manupulation


In [105]:
arr2 = np.random.randint(1,10,(4,4))

In [106]:
arr2

array([[1, 1, 6, 1],
       [7, 1, 8, 5],
       [2, 6, 9, 1],
       [2, 1, 4, 8]])

In [107]:
arr2.reshape(8,2)

array([[1, 1],
       [6, 1],
       [7, 1],
       [8, 5],
       [2, 6],
       [9, 1],
       [2, 1],
       [4, 8]])

In [108]:
arr2.T

array([[1, 7, 2, 2],
       [1, 1, 6, 1],
       [6, 8, 9, 4],
       [1, 5, 1, 8]])

In [109]:
arr2.flatten()

array([1, 1, 6, 1, 7, 1, 8, 5, 2, 6, 9, 1, 2, 1, 4, 8])

In [110]:
np.expand_dims(arr2,axis = 1)

array([[[1, 1, 6, 1]],

       [[7, 1, 8, 5]],

       [[2, 6, 9, 1]],

       [[2, 1, 4, 8]]])

In [111]:
np.expand_dims(arr2,axis = 0)

array([[[1, 1, 6, 1],
        [7, 1, 8, 5],
        [2, 6, 9, 1],
        [2, 1, 4, 8]]])

In [115]:
np.expand_dims(arr2,axis = 1)

array([[[1, 1, 6, 1]],

       [[7, 1, 8, 5]],

       [[2, 6, 9, 1]],

       [[2, 1, 4, 8]]])

In [116]:
# Array Manupulation

In [118]:
arr100 = np.random.randint(1,10,(4,4))

In [119]:
arr100.reshape(8,2)

array([[9, 4],
       [4, 6],
       [1, 1],
       [8, 5],
       [5, 2],
       [2, 7],
       [1, 5],
       [6, 1]])

In [120]:
np.expand_dims(arr100,axis = 1)

array([[[9, 4, 4, 6]],

       [[1, 1, 8, 5]],

       [[5, 2, 2, 7]],

       [[1, 5, 6, 1]]])

In [121]:
data = np.array([[1],[2],[3]])

In [123]:
np.squeeze(data)

array([1, 2, 3])

In [124]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [126]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [127]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [129]:
# Binary Operators

In [131]:
arr1 = np.random.randint(1,10,(3,4))

In [132]:
arr2 = np.random.randint(1,10,(3,4))

In [133]:
arr1

array([[9, 3, 2, 3],
       [6, 6, 9, 7],
       [6, 5, 7, 3]])

In [134]:
arr2

array([[6, 1, 4, 8],
       [1, 5, 2, 7],
       [4, 5, 3, 5]])

In [135]:
arr1+arr2

array([[15,  4,  6, 11],
       [ 7, 11, 11, 14],
       [10, 10, 10,  8]])

In [137]:
arr1@arr2.T

array([[ 89,  49,  72],
       [134, 103, 116],
       [ 93,  66,  85]])

In [138]:
~arr1

array([[-10,  -4,  -3,  -4],
       [ -7,  -7, -10,  -8],
       [ -7,  -6,  -8,  -4]], dtype=int32)

In [139]:
#String Operations

In [140]:
arr = np.array(["Hello","Sharath"])

In [142]:
arr12 = np.char.upper(arr)

In [143]:
np.char.capitalize(arr12)

array(['Hello', 'Sharath'], dtype='<U7')

In [144]:
np.char.title(arr12)

array(['Hello', 'Sharath'], dtype='<U7')

In [145]:
# Mathematical Functions

In [146]:
arr1

array([[9, 3, 2, 3],
       [6, 6, 9, 7],
       [6, 5, 7, 3]])

In [147]:
np.sin(arr1)

array([[ 0.41211849,  0.14112001,  0.90929743,  0.14112001],
       [-0.2794155 , -0.2794155 ,  0.41211849,  0.6569866 ],
       [-0.2794155 , -0.95892427,  0.6569866 ,  0.14112001]])

In [148]:
np.cos(arr1)

array([[-0.91113026, -0.9899925 , -0.41614684, -0.9899925 ],
       [ 0.96017029,  0.96017029, -0.91113026,  0.75390225],
       [ 0.96017029,  0.28366219,  0.75390225, -0.9899925 ]])

In [149]:
np.tan(arr1)

array([[-0.45231566, -0.14254654, -2.18503986, -0.14254654],
       [-0.29100619, -0.29100619, -0.45231566,  0.87144798],
       [-0.29100619, -3.38051501,  0.87144798, -0.14254654]])

In [150]:
np.log10(arr1)

array([[0.95424251, 0.47712125, 0.30103   , 0.47712125],
       [0.77815125, 0.77815125, 0.95424251, 0.84509804],
       [0.77815125, 0.69897   , 0.84509804, 0.47712125]])

In [151]:
np.exp(arr1)

array([[8.10308393e+03, 2.00855369e+01, 7.38905610e+00, 2.00855369e+01],
       [4.03428793e+02, 4.03428793e+02, 8.10308393e+03, 1.09663316e+03],
       [4.03428793e+02, 1.48413159e+02, 1.09663316e+03, 2.00855369e+01]])

In [152]:
np.power(arr1,2)

array([[81,  9,  4,  9],
       [36, 36, 81, 49],
       [36, 25, 49,  9]], dtype=int32)

In [153]:
np.mean(arr1)

5.5

In [155]:
np.median(arr1)

6.0

In [156]:
np.std(arr1)

2.254624876411447

In [157]:
np.var(arr1)

5.083333333333333

In [158]:
np.min(arr1)

2

In [159]:
# Arithmetic Operations

In [161]:
np.subtract(arr1,arr2)

array([[ 3,  2, -2, -5],
       [ 5,  1,  7,  0],
       [ 2,  0,  4, -2]])

In [162]:
np.multiply(arr1,arr2)

array([[54,  3,  8, 24],
       [ 6, 30, 18, 49],
       [24, 25, 21, 15]])

In [163]:
np.mod(arr1,arr2)

array([[3, 0, 2, 3],
       [0, 1, 1, 0],
       [2, 0, 1, 3]], dtype=int32)

In [164]:
np.power(arr1,arr2)

array([[531441,      3,     16,   6561],
       [     6,   7776,     81, 823543],
       [  1296,   3125,    343,    243]], dtype=int32)

In [165]:
np.sqrt(arr1)

array([[3.        , 1.73205081, 1.41421356, 1.73205081],
       [2.44948974, 2.44948974, 3.        , 2.64575131],
       [2.44948974, 2.23606798, 2.64575131, 1.73205081]])

In [166]:
# Statistical Functions

In [167]:
np.mean(arr1)

5.5

In [168]:
np.std(arr1)

2.254624876411447

In [169]:
np.median(arr2)

4.5

In [170]:
# Search and counting functions

In [176]:
arr = np.array([1,2,3,4,5,4,5,3,5,3,5,2,353,231,4,2,32,3,43,6])

In [177]:
np.sort(arr)

array([  1,   2,   2,   2,   3,   3,   3,   3,   4,   4,   4,   5,   5,
         5,   5,   6,  32,  43, 231, 353])

In [181]:
np.searchsorted(arr,3)

2

In [182]:
arr1 = np.array([23,432,42,23,54,2,4335,3,23,0,99,9,8,8,7,7,6,6])

In [183]:
np.count_nonzero(arr1)

17

In [188]:
np.where(arr1>10)

(array([ 0,  1,  2,  3,  4,  6,  8, 10], dtype=int64),)

In [190]:
np.extract(arr1>10,arr1)

array([  23,  432,   42,   23,   54, 4335,   23,   99])

In [191]:
#Byte supllying


In [196]:
arr1.byteswap(True)

array([  385875968, -1342111744,   704643072,   385875968,   905969664,
          33554432,  -284164096,    50331648,   385875968,           0,
        1660944384,   150994944,   134217728,   134217728,   117440512,
         117440512,   100663296,   100663296])

In [193]:
arr1

array([  23,  432,   42,   23,   54,    2, 4335,    3,   23,    0,   99,
          9,    8,    8,    7,    7,    6,    6])

In [198]:
# Copies & Views

In [199]:
a = np.copy(arr1)

In [200]:
a

array([  385875968, -1342111744,   704643072,   385875968,   905969664,
          33554432,  -284164096,    50331648,   385875968,           0,
        1660944384,   150994944,   134217728,   134217728,   117440512,
         117440512,   100663296,   100663296])

In [202]:
arr1

array([  385875968, -1342111744,   704643072,   385875968,   905969664,
          33554432,  -284164096,    50331648,   385875968,           0,
        1660944384,   150994944,   134217728,   134217728,   117440512,
         117440512,   100663296,   100663296])

In [207]:
b = arr1.view()

In [208]:
b

array([  385875968, -1342111744,   704643072,   385875968,   905969664,
          33554432,  -284164096,    50331648,   385875968,           0,
        1660944384,   150994944,   134217728,   134217728,   117440512,
         117440512,   100663296,   100663296])

In [209]:
b[0]= 100

In [210]:
b

array([        100, -1342111744,   704643072,   385875968,   905969664,
          33554432,  -284164096,    50331648,   385875968,           0,
        1660944384,   150994944,   134217728,   134217728,   117440512,
         117440512,   100663296,   100663296])

In [211]:
# MAtrix library

In [213]:
import numpy.matlib as nm

In [215]:
nm.zeros((3,5))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [217]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [218]:
# Linear Algebra

In [219]:
arr1

array([        100, -1342111744,   704643072,   385875968,   905969664,
          33554432,  -284164096,    50331648,   385875968,           0,
        1660944384,   150994944,   134217728,   134217728,   117440512,
         117440512,   100663296,   100663296])

In [221]:
arr1 = np.random.randint([[2,3],[4,5]])

In [223]:
arr2 = np.random.randint([[5,3],[2,5]])

In [224]:
arr1

array([[1, 0],
       [2, 0]])

In [225]:
arr2

array([[4, 0],
       [0, 2]])

In [226]:
np.dot(arr1,arr2)

array([[4, 0],
       [8, 0]])

In [227]:
arr1@arr2

array([[4, 0],
       [8, 0]])